export const setGroupers = 'grouperConsult/setGroupers'
export const setFilterTerm = 'grouperConsult/setFilterTerm'
export const setFilterProperties = 'grouperConsult/setFilterProperties'
export const setGrouper = 'grouperConsult/setGrouper'
export const setGrouperProjects = 'grouperConsult/setGrouperProjects'
