export const groupers = 'grouperConsult/groupers'
export const filterTerm = 'grouperConsult/filterTerm'
export const filterProperties = 'grouperConsult/filterProperties'
export const grouper = 'grouperConsult/grouper'
export const grouperProjects = 'grouperConsult/grouperProjects'
