export const data = 'data'
export const ofTestManufsAndSystems = 'ofTestManufsAndSystems'
export const ofDevManufsAndSystems = 'ofDevManufsAndSystems'
export const filterTerm = 'filterTerm'
export const selected = 'selected'
export const loading = 'loading'
