export const defects = 'defects'
export const loading = 'loading'
export const selectedDefect = 'selectedDefect'
export const selectedDefectDetail = 'selectedDefectDetail'
export const selectedDefectTime = 'selectedDefectTime'
export const status = 'status'
