export const pulledChainProjects = 'pulledChain/pulledChainProjects'
export const pulledChainProjectsFilteredByText = 'pulledChain/pulledChainProjectsFilteredByText'
export const pulledChainFilterTerm = 'pulledChain/pulledChainFilterTerm'
export const pulledChainProjectSelected = 'pulledChain/pulledChainProject'
export const updatePulledChainProjectSelected = 'pulledChain/updatePulledChainProjectSelected'
